// <auto-generated />
using System;
using Cine__backend.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cine__backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210608173440_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cine__backend.Models.BookEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Expense")
                        .HasColumnType("float");

                    b.Property<double>("Income")
                        .HasColumnType("float");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookEntries");
                });

            modelBuilder.Entity("Cine__backend.Models.ClubMember", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("ClubMembers");
                });

            modelBuilder.Entity("Cine__backend.Models.ClubMemberGenre", b =>
                {
                    b.Property<Guid>("ClubMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClubMemberId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("clubMemberGenres");
                });

            modelBuilder.Entity("Cine__backend.Models.Film", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("Cine__backend.Models.FilmFilmRol", b =>
                {
                    b.Property<Guid>("FilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilmRolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MemberRol")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FilmId", "FilmRolId", "MemberRol");

                    b.HasIndex("FilmRolId");

                    b.ToTable("FilmFilmRols");
                });

            modelBuilder.Entity("Cine__backend.Models.FilmGenre", b =>
                {
                    b.Property<Guid>("FilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FilmId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("FilmGenres");
                });

            modelBuilder.Entity("Cine__backend.Models.FilmRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FilmRols");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0aebe5dc-f434-4d90-a0c6-56633b2548a0"),
                            Name = "Actor"
                        },
                        new
                        {
                            Id = new Guid("467a57d2-a478-4dcc-bb2e-0bdce570bedc"),
                            Name = "Director"
                        },
                        new
                        {
                            Id = new Guid("e2a37e14-6568-457e-9ba2-2fa8728dd38a"),
                            Name = "Productor"
                        },
                        new
                        {
                            Id = new Guid("cc0d1d05-eb0c-4f85-aaa4-c69692f6e419"),
                            Name = "Asistente de dirección"
                        },
                        new
                        {
                            Id = new Guid("90028982-7c11-445d-873d-58d62e06f291"),
                            Name = "Productor Ejecutivo"
                        },
                        new
                        {
                            Id = new Guid("6ce98246-0381-42ed-af08-62fbe8438028"),
                            Name = "Guionista"
                        },
                        new
                        {
                            Id = new Guid("8987b25c-812f-4aac-bef5-ceb9f775c720"),
                            Name = "Diseñador de Vestuario"
                        },
                        new
                        {
                            Id = new Guid("a549a375-6ee0-47d8-9660-d2ee900c916c"),
                            Name = "Técnico de Sonido"
                        });
                });

            modelBuilder.Entity("Cine__backend.Models.FilmScreening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StarTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("RoomId");

                    b.ToTable("FilmScreenings");
                });

            modelBuilder.Entity("Cine__backend.Models.FilmScreeningPriceModification", b =>
                {
                    b.Property<Guid>("FilmScreeningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PriceModificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Optional")
                        .HasColumnType("bit");

                    b.HasKey("FilmScreeningId", "PriceModificationId");

                    b.HasIndex("PriceModificationId");

                    b.ToTable("FilmScreeningPriceModifications");
                });

            modelBuilder.Entity("Cine__backend.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84eeee98-c73d-4883-9c63-79f824b0ae65"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("90d25f73-b702-46a1-8490-af10a4b54c65"),
                            Name = "Comedia"
                        },
                        new
                        {
                            Id = new Guid("1726faa4-9a5d-4c73-955e-3158f4c68867"),
                            Name = "Romántica"
                        },
                        new
                        {
                            Id = new Guid("bb470b9f-e073-41bf-9200-b49aff0a3725"),
                            Name = "Suspenso"
                        },
                        new
                        {
                            Id = new Guid("d0f80de4-f257-409b-bd4b-81b442ae97ed"),
                            Name = "Terror"
                        },
                        new
                        {
                            Id = new Guid("5e3564c2-4435-4e82-a7a4-5736c62d57a5"),
                            Name = "Tragicomedia"
                        },
                        new
                        {
                            Id = new Guid("ce0d061e-a46d-4818-b82f-b097d191f45d"),
                            Name = "Hístorico"
                        },
                        new
                        {
                            Id = new Guid("4f35d70b-0348-4ae4-9a19-8bee077d58e4"),
                            Name = "Documental"
                        },
                        new
                        {
                            Id = new Guid("26e8ddf5-3bba-4943-aa9e-318eb0e3d578"),
                            Name = "Ficción"
                        },
                        new
                        {
                            Id = new Guid("823e7646-6013-4b16-9141-d41ef00e4092"),
                            Name = "Ciencia Ficción"
                        },
                        new
                        {
                            Id = new Guid("0d5ee7c4-c1ae-4bce-82bc-f9d3c413e7a0"),
                            Name = "Aventura"
                        },
                        new
                        {
                            Id = new Guid("355a4e39-442c-4a4f-ab65-50414ea971fe"),
                            Name = "Musical"
                        },
                        new
                        {
                            Id = new Guid("2f63347a-9aa5-4f41-909e-5ac15e434c4a"),
                            Name = "Erótico"
                        });
                });

            modelBuilder.Entity("Cine__backend.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("Cine__backend.Models.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Cine__backend.Models.PriceModification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PriceModifications");
                });

            modelBuilder.Entity("Cine__backend.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoxOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CredictCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Cine__backend.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Cine__backend.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Cine__backend.Models.SeatSectionLevelRoom", b =>
                {
                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SeatId", "SectionId", "LevelId", "RoomId");

                    b.HasIndex("LevelId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SectionId");

                    b.ToTable("SeatSectionLevelRooms");
                });

            modelBuilder.Entity("Cine__backend.Models.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Cine__backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Cine__backend.Models.UserFilm", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("UserId", "FilmId");

                    b.HasIndex("FilmId");

                    b.ToTable("UserFilms");
                });

            modelBuilder.Entity("Cine__backend.Models.Reservation", b =>
                {
                    b.HasBaseType("Cine__backend.Models.Item");

                    b.Property<Guid>("FilmSreeningId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasIndex("FilmSreeningId");

                    b.HasIndex("SeatId");

                    b.HasDiscriminator().HasValue("Reservation");
                });

            modelBuilder.Entity("Cine__backend.Models.ClubMemberGenre", b =>
                {
                    b.HasOne("Cine__backend.Models.ClubMember", "ClubMember")
                        .WithMany()
                        .HasForeignKey("ClubMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClubMember");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Cine__backend.Models.FilmFilmRol", b =>
                {
                    b.HasOne("Cine__backend.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.FilmRol", "FilmRol")
                        .WithMany()
                        .HasForeignKey("FilmRolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("FilmRol");
                });

            modelBuilder.Entity("Cine__backend.Models.FilmGenre", b =>
                {
                    b.HasOne("Cine__backend.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Cine__backend.Models.FilmScreening", b =>
                {
                    b.HasOne("Cine__backend.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Cine__backend.Models.FilmScreeningPriceModification", b =>
                {
                    b.HasOne("Cine__backend.Models.FilmScreening", "FilmScreening")
                        .WithMany()
                        .HasForeignKey("FilmScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.PriceModification", "PriceModification")
                        .WithMany()
                        .HasForeignKey("PriceModificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmScreening");

                    b.Navigation("PriceModification");
                });

            modelBuilder.Entity("Cine__backend.Models.Item", b =>
                {
                    b.HasOne("Cine__backend.Models.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Cine__backend.Models.PurchaseOrder", b =>
                {
                    b.HasOne("Cine__backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cine__backend.Models.SeatSectionLevelRoom", b =>
                {
                    b.HasOne("Cine__backend.Models.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Room");

                    b.Navigation("Seat");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Cine__backend.Models.UserFilm", b =>
                {
                    b.HasOne("Cine__backend.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Cine__backend.Models.Reservation", b =>
                {
                    b.HasOne("Cine__backend.Models.FilmScreening", "FilmScreening")
                        .WithMany()
                        .HasForeignKey("FilmSreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cine__backend.Models.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmScreening");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Cine__backend.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
