// <auto-generated />
using System;
using Cine__backend.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cine__backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cine__backend.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db683059-0055-40ee-98aa-a413b80bd677"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("75fb3cd7-94bf-4dde-8e56-2e2a0d91a261"),
                            Name = "Comedia"
                        },
                        new
                        {
                            Id = new Guid("c8693cb0-09ab-4eb1-9945-c0f389ba539a"),
                            Name = "Romántica"
                        },
                        new
                        {
                            Id = new Guid("fccdc11b-7a19-4bbb-9ad7-ae5d378131c1"),
                            Name = "Suspenso"
                        },
                        new
                        {
                            Id = new Guid("6195ebc3-2717-4c5a-9bb8-412e329ca9dd"),
                            Name = "Terror"
                        });
                });

            modelBuilder.Entity("Cine__backend.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
